apiVersion: v1
kind: Namespace
metadata:
  name: ac3no
---
apiVersion: ac3.redhat.com/v1alpha1
kind: SkupperRouter
metadata:
  name: example-skupperrouter
  namespace: ac3no  # Ensure this field is properly set
spec:
  name: Hello, World!
  namespace: ac3no  # Ensure this field is properly set in the spec
