apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-manager-rolebinding
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: sk1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller-manager-role  # Ensure this is the correct ClusterRole name
