apiVersion: v1
kind: ConfigMap
metadata:
  name: ac3-combined-kubeconfig
  namespace: sk1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        insecure-skip-tls-verify: true
        server: https://api.ac3-cluster-1.rh-horizon.eu:6443
      name: ac3-cluster-1
    - cluster:
        insecure-skip-tls-verify: true
        server: https://api.ac3-cluster-2.rh-horizon.eu:6443
      name: ac3-cluster-2
    contexts:
    - context:
        cluster: ac3-cluster-1
        namespace: default
        user: ac3-cluster-1
      name: ac3-cluster-1
    - context:
        cluster: ac3-cluster-2
        namespace: sk1
        user: ac3-cluster-2
      name: ac3-cluster-2
    current-context: ac3-cluster-2
    kind: Config
    preferences: {}
    users:
    - name: ac3-cluster-1
      user:
        token: 
    - name: ac3-cluster-2
      user:
        token: 
