apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ac3-network-controller
  namespace: sk2
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
