apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ac3no
  name: controller-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["ac3.redhat.com"]
  resources: ["ac3networks", "skupperrouters"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["ac3.redhat.com"]
  resources: ["ac3networks/status", "skupperrouters/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["ac3.redhat.com"]
  resources: ["ac3networks/finalizers", "skupperrouters/finalizers"]
  verbs: ["update"]
