apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ac3-network-controller-binding
  namespace: sk2
subjects:
- kind: ServiceAccount
  name: default
  namespace: sk2
roleRef:
  kind: Role
  name: ac3-network-controller
  apiGroup: rbac.authorization.k8s.io
