apiVersion: ac3.redhat.com/v1alpha1
kind: MultiClusterNetwork
metadata:
  name: multiclusternetwork
  namespace: ac3no
spec:
  links:
      - sourceCluster: "cluster-2"
        targetCluster: "cluster-4"
        sourceNamespace: "test3"
        targetNamespace: "test4"
        services:
          - "backend"
        port: 8080
      - sourceCluster: "cluster-3"
        targetCluster: "cluster-4"
        sourceNamespace: "multiclusternetwork-test"
        targetNamespace: "multiclusternetwork-test1"
        services:
          - "backend"
        port: 8080

