apiVersion: ac3.redhat.com/v1alpha1
kind: MultiClusterNetwork
metadata:
  name: multiclusternetwork
  namespace: ac3no
spec:
  links:
      - sourceCluster: "cluster-1"
        targetCluster: "cluster-3"
        sourceNamespace: "default"
        targetNamespace: "default"
        services:
          - "backend"
        port: 8080
      - sourceCluster: "cluster-2"
        targetCluster: "cluster-3"
        sourceNamespace: "sk2"
        targetNamespace: "sk8"
        services:
          - "backend"
        port: 8080
      - sourceCluster: "cluster-2"
        targetCluster: "cluster-3"
        sourceNamespace: "sk3"
        targetNamespace: "sk5"
        services:
          - "backend"
        port: 8080

      

