apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx3
  # annotations:
  #   skupper.io/proxy: tcp
  name: nginx3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx3
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:stable-alpine
        imagePullPolicy: IfNotPresent
        name: nginx3
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        terminationGracePeriodSeconds: 30
