apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    # annotations:
    #   skupper.io/proxy: tcp
  name: ryan3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: nginxinc/nginx-unprivileged:stable-alpine
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File