apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: skupperrouters.ac3.redhat.com
spec:
  group: ac3.redhat.com
  names:
    kind: SkupperRouter
    listKind: SkupperRouterList
    plural: skupperrouters
    singular: skupperrouter
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                port:
                  type: integer
                protocol:
                  type: string
          